// src/routes/buong-kuwento/+page.svelte
<script lang="ts">
	import StoryHeroSection from '@/components/story-hero-section.svelte';
	import { fullStoryChapters } from '@/data';
	import BuongKuwentoCover from '@/assets/stories/buong-kuwento-cover.png';
</script>

<svelte:head>
	<title>Buong Kuwento: Table of Contents</title>
</svelte:head>

<StoryHeroSection imageCover={BuongKuwentoCover} />

<section class="min-h-screen bg-surface-100 p-8 text-surface-content">
	<div class="container mx-auto max-w-4xl">
		<h1 class="mb-6 text-center text-4xl font-semibold">Buong Kuwento</h1>
		<p class="mb-8 text-center text-lg text-surface-content/80">
			Piliin ang pahina upang simulan ang iyong pagbabasa.
		</p>
		<div class="grid md:grid-cols-2 gap-4">
			{#each fullStoryChapters as chapter}
				<a
					href="/buong-kuwento{chapter.link}"
					class="block space-y-2 rounded-lg border border-primary/30 bg-white p-4 shadow-md transition hover:shadow-lg"
				>
					<h3 class="text-xl font-medium text-[#2D2522]">{chapter.title}</h3>
					<p class="text-sm text-[#2D2522]/80">
						{chapter.content.slice(0, 200)}...
					</p>
				</a>
			{/each}
		</div>
	</div>
</section>

// src/components/stories/buong-kuwento/buong-kuwento.tsx
import storiesContents from "@/data/stories-contents";
import { Metadata } from "next";
import { useState } from "react";
import ChapterButton from "./_components/chapter-button";
import NavButtons from "./_components/nav-buttons";
import PaginatedChapterReader from "./_components/paginated-chapter-reader";

export const metadata: Metadata = {
    title: "Buong Kuwento",
};

const BuongKuwento = () => {
    const [activeChapterIndex, setActiveChapterIndex] = useState<number>(-1);

    const storyChapter = storiesContents[activeChapterIndex];
    const nextChapter = storiesContents[activeChapterIndex + 1] || null;
    const previousChapter = storiesContents[activeChapterIndex - 1] || null;

    return (
        <section className="relative min-h-screen bg-gradient-to-b from-white to-primary/5 px-4 py-6 text-surface-content md:px-8">
            {activeChapterIndex >= 0 ? (
                <div className="container mx-auto space-y-12 px-2 md:px-[10%]">
                    <div className="space-y-4">
                        <h3 className="text-2xl text-center font-bold text-secondary">
                            {storyChapter.title}
                        </h3>

                        <PaginatedChapterReader
                            content={storyChapter.content}
                            isLastPage={!nextChapter}
                        />
                    </div>

                    <div className="w-full border-t border-secondary/20" />

                    <NavButtons
                        prev={previousChapter}
                        next={nextChapter}
                        onHomeClick={() => setActiveChapterIndex(-1)}
                        onPrevClick={() =>
                            setActiveChapterIndex(activeChapterIndex - 1)
                        }
                        onNextClick={() =>
                            setActiveChapterIndex(activeChapterIndex + 1)
                        }
                    />
                </div>
            ) : (
                <div className="flex flex-col items-center space-y-4 text-center">
                    <p className="mx-auto max-w-2xl text-lg text-surface-content/80">
                        Piliin ang pahina upang simulan ang iyong pagbabasa
                    </p>

                    <div className="lg:w-3/4 grid gap-6 md:grid-cols-2">
                        {storiesContents.map((chapter, i) => (
                            <ChapterButton
                                key={chapter.link}
                                chapter={chapter}
                                onClick={() => {
                                    setActiveChapterIndex(i);
                                }}
                            />
                        ))}
                    </div>
                </div>
            )}
        </section>
    );
};

export default BuongKuwento;
