// src/lib/layout/footer.svelte
<script lang="ts">
	let year = new Date().getFullYear();
</script>

<footer class="bg-secondary py-8">
	<div class="container mx-auto px-4">
		<div class="flex flex-col items-center justify-center space-y-4">
      <!-- TODO: add social media links -->
			<div class="flex space-x-6">
				<a href="#" class="text-gray-400 transition-colors hover:text-white">
					<!-- <Facebook class="h-6 w-6" /> -->
				</a>
				<a href="#" class="text-gray-400 transition-colors hover:text-white">
					<!-- <Instagram class="h-6 w-6" /> -->
				</a>
				<a href="#" class="text-gray-400 transition-colors hover:text-white">
					<!-- <Twitter class="h-6 w-6" /> -->
				</a>
			</div>
			<p class="text-center text-sm text-secondary-content/60">
				Copyright &copy; {year}, TalasTasan. All Rights Reserved.
			</p>
		</div>
	</div>
</footer>

// src/components/layouts/footer.tsx
const Footer = () => {
  const year = new Date().getFullYear();

  return (
    <footer className="bg-secondary py-8">
      <div className="container mx-auto px-4">
        <div className="flex flex-col items-center justify-center space-y-4">
          <p className="text-center text-sm text-secondary-content/60">
            Copyright &copy;{year}, TalasTasan. All Rights Reserved.
          </p>
        </div>
      </div>
    </footer>
  );
};

export default Footer;
