// src/lib/layout/header.svelte
<script lang="ts">
	import Logo from '@/assets/logo.png?enhanced';
	import NavMenu from '@/components/nav-menu.svelte';
	import { onMount } from 'svelte';

	let isScrolled = $state(false);

	onMount(() => {
		const handleScroll = () => {
			isScrolled = window.scrollY > 0;
		};

		window.addEventListener('scroll', handleScroll);

		return () => {
			window.removeEventListener('scroll', handleScroll);
		};
	});
</script>

<header
	class="fixed z-50 flex w-full flex-row items-center justify-between bg-secondary px-4 py-3 text-primary-content transition-all duration-150 md:px-8"
	style="--tw-bg-opacity: {isScrolled ? 1 : 0}"
>
	<a href="/" class="flex w-fit flex-row items-center gap-2">
		<enhanced:img src={Logo} alt="logo" class="w-12" />
		<h1 class="text-lg font-bold">TalasTasan</h1>
	</a>
	<NavMenu />
</header>

// src/components/layouts/header.tsx
"use client";

import Logo from "@/assets/images/logo.png";
import Image from "next/image";
import Link from "next/link";
import { useEffect, useState } from "react";

const Header = () => {
  const [isScrolled, setIsScrolled] = useState(false);

  useEffect(() => {
    const handleScroll = () => {
      setIsScrolled(window.scrollY > 0);
    };

    window.addEventListener("scroll", handleScroll);

    return () => {
      window.removeEventListener("scroll", handleScroll);
    };
  }, []);

  return (
    <header
      className={`fixed z-50 w-full flex items-center justify-between px-4 py-3 transition-all duration-150 md:px-8 ${
        isScrolled ? "bg-secondary shadow-lg" : "bg-transparent"
      } text-primary-foreground`}
    >
      <Link href="/" className="flex items-center gap-2">
        <Image src={Logo} alt="logo" className="w-12" />
        <h1 className="text-lg font-bold">TalasTasan</h1>
      </Link>
      {/* <NavMenu /> */}
    </header>
  );
};

export default Header;
