// src/components/cards/story-card.tsx
import Image, { StaticImageData } from "next/image";

interface StoryCardProps {
  title: string;
  description: string;
  image: StaticImageData | string; // Use string for image src unless using a specific type for assets
  href: string;
}

const StoryCard: React.FC<StoryCardProps> = ({
  title,
  description,
  image,
  href,
}) => {
  return (
    <a
      href={href}
      className="group relative overflow-hidden rounded-lg border border-primary/30 bg-white transition-transform hover:-translate-y-1"
    >
      <div className="relative aspect-video overflow-hidden">
        <Image
          src={image}
          alt={title}
          layout="fill" // Adjusts the image to fill its parent container
          objectFit="cover" // Ensures the image is cropped correctly
          className="transition-transform group-hover:scale-100"
        />
      </div>
      <div className="p-6">
        <h3 className="mb-3 text-xl font-semibold text-[#2D2522]">{title}</h3>
        <p className="text-gray-600">{description}</p>
      </div>
    </a>
  );
};

export default StoryCard;

// src/lib/components/story-card.svelte
<script lang="ts" module>
	interface StoryCardProps {
		title: string;
		description: string;
		image: any;
		href: string;
	}
</script>

<script lang="ts">
	export let title: StoryCardProps['title'];
	export let description: StoryCardProps['description'];
	export let image: StoryCardProps['image'];
	export let href: StoryCardProps['href'];
</script>

<div
	class="border-primary/30 group relative overflow-hidden rounded-lg border bg-white transition-transform hover:-translate-y-1"
>
	<a {href}>
		<div class="relative aspect-video overflow-hidden">
			<enhanced:img
				src={image}
				alt={title}
				class="object-cover transition-transform group-hover:scale-100"
			/>
		</div>
		<div class="p-6">
			<h3 class="mb-3 text-xl font-semibold text-[#2D2522]">{title}</h3>
			<p class="text-gray-600">{description}</p>
		</div>
	</a>
</div>
