// src/app/(contents)/kuwentong-may-larawan/page.tsx
import storyWithImages from "@/data/story-with-images";
import PageTitle from "../_components/page-title";
import AnimatedStoryViewer from "./_components/animated-story-viewer";

const Page = () => {
  return (
    <section className="bg-surface-100">
      <PageTitle title="Kuwentong May Larawan" />
      <div className="container mx-auto w-fit p-2 md:py-12">
        <div className="mx-auto w-full md:w-[875px] space-y-4">
          <AnimatedStoryViewer className="w-full" slides={storyWithImages} />
        </div>
      </div>
    </section>
  );
};

export default Page;

// src/routes/kuwentong-may-larawan/+page.svelte
<script lang="ts">
	import KuwentongMayLarawanCover from '@/assets/stories/kuwentong-may-larawan-cover.png';
	import StoryHeroSection from '@/components/story-hero-section.svelte';
	import PageTitle from '@/components/page-title.svelte';
</script>

<svelte:head>
	<title>Kuwentong May Larawan | TalasTasan</title>
</svelte:head>

<!-- Hero -->
<StoryHeroSection imageCover={KuwentongMayLarawanCover} />

<section class="bg-surface-100">
	<PageTitle title="Kuwentong May Larawan" />
</section>
